from typing import Protocol

import numpy as np


class Model(Protocol):
    def update(self) -> np.ndarray: ...


class View(Protocol):
    def set_title(self, title: str) -> None: ...
    def connect_event(self, event_name: str, callback) -> int: ...
    def disconnect_event(self, cid: int) -> None: ...
    def show(self, block: bool = False) -> None: ...
    def update_initial_state(self, i: int, j: int) -> None: ...
    def refresh(self) -> None: ...
    def get_initial_state(self) -> np.ndarray: ...
    def get_figure(self): ...
    def display(self, state: np.ndarray, generations: int) -> None: ...
